export const DEFAULT_MEALS = [
  // ── BREAKFAST ──────────────────────────────────────────────────────────
  { item_name:'Scrambled Eggs',        category:'Breakfast', ingredients:'eggs, butter, salt, pepper',              diet_type:'veg',    notes:'https://www.youtube.com/watch?v=PUP7U5vTMM0' },
  { item_name:'Cheese Omelette',       category:'Breakfast', ingredients:'eggs, cheese, butter',                    diet_type:'veg',    notes:'https://www.youtube.com/watch?v=Ds2n0bHv4Uw' },
  { item_name:'Veggie Omelette',       category:'Breakfast', ingredients:'eggs, onion, bell pepper, cheese',         diet_type:'veg',    notes:'https://www.instagram.com/p/CqNxampleVeggieOmelette' },
  { item_name:'Avocado Toast',         category:'Breakfast', ingredients:'bread, avocado, olive oil, salt',          diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=fmhSJAKKMpg' },
  { item_name:'Peanut Butter Toast',   category:'Breakfast', ingredients:'bread, peanut butter',                    diet_type:'vegan',  notes:null },
  { item_name:'Pancakes',              category:'Breakfast', ingredients:'flour, eggs, milk, butter',               diet_type:'veg',    notes:'https://www.youtube.com/watch?v=GHxbvIWjbZI' },
  { item_name:'Banana Pancakes',       category:'Breakfast', ingredients:'banana, eggs, flour, milk',               diet_type:'veg',    notes:'https://www.youtube.com/watch?v=9u9IcNcv8vs' },
  { item_name:'French Toast',          category:'Breakfast', ingredients:'bread, eggs, milk, cinnamon',             diet_type:'veg',    notes:'https://www.youtube.com/watch?v=zGwMnPIPkKc' },
  { item_name:'Greek Yogurt Bowl',     category:'Breakfast', ingredients:'yogurt, honey, berries',                  diet_type:'veg',    notes:'https://www.instagram.com/p/CqNxampleYogurtBowl' },
  { item_name:'Granola Yogurt',        category:'Breakfast', ingredients:'yogurt, granola, honey',                  diet_type:'veg',    notes:null },
  { item_name:'Oatmeal',              category:'Breakfast', ingredients:'oats, milk, honey',                       diet_type:'veg',    notes:'https://www.youtube.com/watch?v=2GEOkVDLb_0' },
  { item_name:'Apple Cinnamon Oatmeal',category:'Breakfast', ingredients:'oats, apple, cinnamon, milk',            diet_type:'veg',    notes:'https://www.youtube.com/watch?v=MgcLrhGBaM8' },
  { item_name:'Smoothie Bowl',         category:'Breakfast', ingredients:'banana, berries, yogurt',                diet_type:'veg',    notes:'https://www.instagram.com/p/CqNxampleSmoothieBowl' },
  { item_name:'Protein Smoothie',      category:'Breakfast', ingredients:'banana, protein powder, milk',           diet_type:'veg',    notes:'https://www.youtube.com/watch?v=2OVvP_KMz2k' },
  { item_name:'Egg Muffins',           category:'Breakfast', ingredients:'eggs, cheese, spinach',                  diet_type:'veg',    notes:'https://www.youtube.com/watch?v=HbjEQHJDqZo' },
  { item_name:'Breakfast Burrito',     category:'Breakfast', ingredients:'eggs, tortilla, cheese, onion',          diet_type:'veg',    notes:'https://www.youtube.com/watch?v=Rkv0lPxwFDU' },
  { item_name:'Bagel & Cream Cheese',  category:'Breakfast', ingredients:'bagel, cream cheese',                    diet_type:'veg',    notes:null },
  { item_name:'Toast & Jam',           category:'Breakfast', ingredients:'bread, jam, butter',                     diet_type:'veg',    notes:null },
  { item_name:'Chia Pudding',          category:'Breakfast', ingredients:'chia seeds, milk, honey',                diet_type:'veg',    notes:'https://www.youtube.com/watch?v=4b0kptnbNEw' },
  { item_name:'Berry Parfait',         category:'Breakfast', ingredients:'yogurt, berries, granola',               diet_type:'veg',    notes:'https://www.instagram.com/p/CqNxampleBerryParfait' },
  { item_name:'Boiled Eggs',           category:'Breakfast', ingredients:'eggs, salt',                             diet_type:'veg',    notes:null },
  { item_name:'Avocado Eggs',          category:'Breakfast', ingredients:'eggs, avocado, olive oil',               diet_type:'veg',    notes:'https://www.youtube.com/watch?v=aAvBpRVKu-8' },
  { item_name:'Cottage Cheese Bowl',   category:'Breakfast', ingredients:'cottage cheese, fruit',                  diet_type:'veg',    notes:null },
  { item_name:'Breakfast Sandwich',    category:'Breakfast', ingredients:'eggs, bread, cheese',                    diet_type:'veg',    notes:'https://www.youtube.com/watch?v=VRGpDFr-Xqw' },
  { item_name:'Spinach Eggs',          category:'Breakfast', ingredients:'eggs, spinach, olive oil',               diet_type:'veg',    notes:'https://www.instagram.com/p/CqNxampleSpinachEggs' },
  { item_name:'Egg Whites Scramble',   category:'Breakfast', ingredients:'egg whites, onion, spinach',             diet_type:'veg',    notes:null },
  { item_name:'Blueberry Muffin',      category:'Breakfast', ingredients:'flour, blueberries, eggs',               diet_type:'veg',    notes:'https://www.youtube.com/watch?v=lKbMVSVHuqY' },
  { item_name:'Chocolate Oatmeal',     category:'Breakfast', ingredients:'oats, cocoa, milk',                      diet_type:'veg',    notes:'https://www.youtube.com/watch?v=Yg_HiYbvzqI' },
  { item_name:'Honey Toast',           category:'Breakfast', ingredients:'bread, honey, butter',                   diet_type:'veg',    notes:null },
  { item_name:'Fruit Salad',           category:'Breakfast', ingredients:'apple, banana, berries',                 diet_type:'vegan',  notes:null },

  // ── LUNCH ──────────────────────────────────────────────────────────────
  { item_name:'Chicken Salad',         category:'Lunch', ingredients:'chicken, lettuce, olive oil',               diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=HHPVS7v8YZo' },
  { item_name:'Grilled Cheese',        category:'Lunch', ingredients:'bread, cheese, butter',                     diet_type:'veg',    notes:'https://www.youtube.com/watch?v=3RL01LGJQPU' },
  { item_name:'Turkey Sandwich',       category:'Lunch', ingredients:'bread, turkey, cheese',                     diet_type:'nonveg', notes:null },
  { item_name:'Veggie Wrap',           category:'Lunch', ingredients:'tortilla, lettuce, tomato, hummus',         diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=aExXkDKoFnI' },
  { item_name:'Pasta Salad',           category:'Lunch', ingredients:'pasta, olive oil, tomato, cheese',          diet_type:'veg',    notes:'https://www.youtube.com/watch?v=XB4X2hTG5kQ' },
  { item_name:'Quinoa Bowl',           category:'Lunch', ingredients:'quinoa, chickpeas, olive oil',              diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=7Kh_gEFkJrA' },
  { item_name:'Rice & Beans',          category:'Lunch', ingredients:'rice, beans, onion, garlic',                diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=mDfMjA0GlJQ' },
  { item_name:'Chicken Rice Bowl',     category:'Lunch', ingredients:'chicken, rice, garlic',                     diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=q5aPnGMbVEI' },
  { item_name:'Tuna Salad',            category:'Lunch', ingredients:'tuna, mayo, onion',                         diet_type:'nonveg', notes:null },
  { item_name:'Egg Salad',             category:'Lunch', ingredients:'eggs, mayo, mustard',                       diet_type:'veg',    notes:'https://www.youtube.com/watch?v=gHBipLjX9F4' },
  { item_name:'Greek Salad',           category:'Lunch', ingredients:'cucumber, tomato, feta, olive oil',         diet_type:'veg',    notes:'https://www.youtube.com/watch?v=b01EM_cqTcw' },
  { item_name:'Lentil Soup',           category:'Lunch', ingredients:'lentils, onion, garlic, carrot',            diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=JMBqAkC2bR0' },
  { item_name:'Chicken Wrap',          category:'Lunch', ingredients:'chicken, tortilla, lettuce',                diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=Uc9q2aNwcNs' },
  { item_name:'Veggie Stir Fry',       category:'Lunch', ingredients:'broccoli, onion, garlic, soy sauce',        diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=OHMeFAoXCb4' },
  { item_name:'Fried Rice',            category:'Lunch', ingredients:'rice, eggs, onion, soy sauce',              diet_type:'veg',    notes:'https://www.youtube.com/watch?v=qH__o17xHls' },
  { item_name:'Pesto Pasta',           category:'Lunch', ingredients:'pasta, basil, olive oil, garlic',           diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=EjH-pMcFoJ8' },
  { item_name:'Chickpea Salad',        category:'Lunch', ingredients:'chickpeas, tomato, onion',                  diet_type:'vegan',  notes:'https://www.instagram.com/p/CqNxampleChickpeaSalad' },
  { item_name:'Tomato Soup',           category:'Lunch', ingredients:'tomato, garlic, onion',                     diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=JOWnflDKCvU' },
  { item_name:'Grilled Veggies',       category:'Lunch', ingredients:'zucchini, bell pepper, olive oil',          diet_type:'vegan',  notes:null },
  { item_name:'Hummus Bowl',           category:'Lunch', ingredients:'hummus, pita, cucumber',                    diet_type:'vegan',  notes:null },
  { item_name:'Avocado Rice',          category:'Lunch', ingredients:'rice, avocado, olive oil',                  diet_type:'vegan',  notes:'https://www.instagram.com/p/CqNxampleAvocadoRice' },
  { item_name:'Chicken Quesadilla',    category:'Lunch', ingredients:'chicken, tortilla, cheese',                 diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=pn3ysATFgxM' },
  { item_name:'Bean Burrito',          category:'Lunch', ingredients:'beans, tortilla, cheese',                   diet_type:'veg',    notes:'https://www.youtube.com/watch?v=o4ck7HEdEYM' },
  { item_name:'Spinach Pasta',         category:'Lunch', ingredients:'pasta, spinach, garlic',                    diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=aCNVMHRjOhM' },
  { item_name:'Curry Lentils',         category:'Lunch', ingredients:'lentils, onion, spices',                    diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=MkVk5MJj-ec' },
  { item_name:'Salmon Rice',           category:'Lunch', ingredients:'salmon, rice, olive oil',                   diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=gMbgH8kAz_Y' },
  { item_name:'Chicken Soup',          category:'Lunch', ingredients:'chicken, carrot, onion',                    diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=kBtNtcU_-3s' },
  { item_name:'Veggie Burger',         category:'Lunch', ingredients:'veggie patty, bun, lettuce',                diet_type:'veg',    notes:'https://www.youtube.com/watch?v=mTGIEj-mVvY' },
  { item_name:'Mac & Cheese',          category:'Lunch', ingredients:'pasta, cheese, milk',                       diet_type:'veg',    notes:'https://www.youtube.com/watch?v=FUeyrEN14Rk' },
  { item_name:'Caprese Sandwich',      category:'Lunch', ingredients:'bread, tomato, mozzarella',                 diet_type:'veg',    notes:'https://www.instagram.com/p/CqNxampleCaprese' },

  // ── DINNER ─────────────────────────────────────────────────────────────
  { item_name:'Chicken Stir Fry',      category:'Dinner', ingredients:'chicken, onion, garlic, soy sauce',        diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=d87Fkdlm3TU' },
  { item_name:'Spaghetti Marinara',    category:'Dinner', ingredients:'pasta, tomato, garlic, olive oil',         diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=YfRE6a5EAbs' },
  { item_name:'Beef Tacos',            category:'Dinner', ingredients:'beef, tortilla, onion, cheese',            diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=lKlpPq3CmHw' },
  { item_name:'Veggie Curry',          category:'Dinner', ingredients:'potato, onion, garlic, spices',            diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=MkVk5MJj-ec' },
  { item_name:'Grilled Salmon',        category:'Dinner', ingredients:'salmon, olive oil, lemon',                 diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=c9bHN_gJPVo' },
  { item_name:'Chicken Alfredo',       category:'Dinner', ingredients:'chicken, pasta, cream, garlic',            diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=5Z5oEbCAvEY' },
  { item_name:'Fried Rice',            category:'Dinner', ingredients:'rice, eggs, onion, soy sauce',             diet_type:'veg',    notes:'https://www.youtube.com/watch?v=qH__o17xHls' },
  { item_name:'Stuffed Peppers',       category:'Dinner', ingredients:'bell pepper, rice, cheese',                diet_type:'veg',    notes:'https://www.youtube.com/watch?v=NTilqpI5WTY' },
  { item_name:'Chicken Parmesan',      category:'Dinner', ingredients:'chicken, cheese, tomato',                  diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=GFe3MO1zWjI' },
  { item_name:'Veggie Pasta',          category:'Dinner', ingredients:'pasta, zucchini, garlic',                  diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=aCNVMHRjOhM' },
  { item_name:'Beef Stir Fry',         category:'Dinner', ingredients:'beef, onion, soy sauce',                   diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=d87Fkdlm3TU' },
  { item_name:'Chickpea Curry',        category:'Dinner', ingredients:'chickpeas, onion, garlic',                 diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=_UbRhPkHgjA' },
  { item_name:'Baked Chicken',         category:'Dinner', ingredients:'chicken, olive oil, spices',               diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=Pb8WuWB6yiA' },
  { item_name:'Lasagna',              category:'Dinner', ingredients:'pasta, cheese, tomato',                    diet_type:'veg',    notes:'https://www.youtube.com/watch?v=y37ULGzg3Ts' },
  { item_name:'Shrimp Rice',           category:'Dinner', ingredients:'shrimp, rice, garlic',                     diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=oE8nU7dYHy4' },
  { item_name:'Veggie Tacos',          category:'Dinner', ingredients:'beans, tortilla, onion',                   diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=IcFnJV6iBas' },
  { item_name:'Chicken Fajitas',       category:'Dinner', ingredients:'chicken, bell pepper, onion',              diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=JBg9FkCT4yY' },
  { item_name:'Pesto Chicken',         category:'Dinner', ingredients:'chicken, basil, olive oil',                diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=OHMeFAoXCb4' },
  { item_name:'Eggplant Parmesan',     category:'Dinner', ingredients:'eggplant, cheese, tomato',                 diet_type:'veg',    notes:'https://www.youtube.com/watch?v=3Kra4cGYYkA' },
  { item_name:'Tofu Stir Fry',         category:'Dinner', ingredients:'tofu, broccoli, soy sauce',                diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=OHMeFAoXCb4' },
  { item_name:'Coconut Curry',         category:'Dinner', ingredients:'coconut milk, potato, onion',              diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=eRPHsZ_kfpA' },
  { item_name:'Meatballs',             category:'Dinner', ingredients:'beef, breadcrumbs, garlic',                diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=j-HUK2sNQe4' },
  { item_name:'Chicken Soup',          category:'Dinner', ingredients:'chicken, carrot, onion',                   diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=kBtNtcU_-3s' },
  { item_name:'Burrito Bowl',          category:'Dinner', ingredients:'rice, beans, chicken',                     diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=CK0YGsn0VhQ' },
  { item_name:'Veggie Chili',          category:'Dinner', ingredients:'beans, tomato, onion',                     diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=rFNqRp1OJ24' },
  { item_name:'Salmon Pasta',          category:'Dinner', ingredients:'salmon, pasta, garlic',                    diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=gMbgH8kAz_Y' },
  { item_name:'Roasted Veggies',       category:'Dinner', ingredients:'potato, carrot, olive oil',                diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=n_-dZSUrsBc' },
  { item_name:'Chicken Tikka',         category:'Dinner', ingredients:'chicken, yogurt, spices',                  diet_type:'nonveg', notes:'https://www.youtube.com/watch?v=a03U45jFxOI' },
  { item_name:'Rice Pilaf',            category:'Dinner', ingredients:'rice, onion, butter',                      diet_type:'veg',    notes:null },
  { item_name:'Stuffed Zucchini',      category:'Dinner', ingredients:'zucchini, rice, cheese',                   diet_type:'veg',    notes:'https://www.youtube.com/watch?v=NTilqpI5WTY' },

  // ── SNACK ───────────────────────────────────────────────────────────────
  { item_name:'Apple & Peanut Butter', category:'Snack', ingredients:'apple, peanut butter',                      diet_type:'vegan',  notes:null },
  { item_name:'Banana',               category:'Snack', ingredients:'banana',                                    diet_type:'vegan',  notes:null },
  { item_name:'Trail Mix',             category:'Snack', ingredients:'nuts, raisins, chocolate',                  diet_type:'veg',    notes:null },
  { item_name:'Yogurt Cup',            category:'Snack', ingredients:'yogurt',                                    diet_type:'veg',    notes:null },
  { item_name:'Cheese & Crackers',     category:'Snack', ingredients:'cheese, crackers',                          diet_type:'veg',    notes:null },
  { item_name:'Granola Bar',           category:'Snack', ingredients:'oats, honey',                               diet_type:'veg',    notes:'https://www.youtube.com/watch?v=RFtMGEe9Aow' },
  { item_name:'Hummus & Carrots',      category:'Snack', ingredients:'hummus, carrots',                           diet_type:'vegan',  notes:null },
  { item_name:'Popcorn',              category:'Snack', ingredients:'corn kernels, salt',                        diet_type:'vegan',  notes:null },
  { item_name:'Protein Bar',           category:'Snack', ingredients:'protein bar',                               diet_type:'veg',    notes:null },
  { item_name:'Fruit Cup',             category:'Snack', ingredients:'fruit',                                     diet_type:'vegan',  notes:null },
  { item_name:'Rice Cakes',            category:'Snack', ingredients:'rice cakes',                                diet_type:'vegan',  notes:null },
  { item_name:'Dark Chocolate',        category:'Snack', ingredients:'chocolate',                                 diet_type:'veg',    notes:null },
  { item_name:'Boiled Egg',            category:'Snack', ingredients:'egg',                                       diet_type:'veg',    notes:null },
  { item_name:'Smoothie',             category:'Snack', ingredients:'banana, milk',                              diet_type:'veg',    notes:'https://www.youtube.com/watch?v=2OVvP_KMz2k' },
  { item_name:'Peanut Handful',        category:'Snack', ingredients:'peanuts',                                   diet_type:'vegan',  notes:null },
  { item_name:'Crackers',             category:'Snack', ingredients:'crackers',                                  diet_type:'vegan',  notes:null },
  { item_name:'Cheese Stick',          category:'Snack', ingredients:'cheese',                                    diet_type:'veg',    notes:null },
  { item_name:'Toast Bites',           category:'Snack', ingredients:'bread, butter',                             diet_type:'veg',    notes:null },
  { item_name:'Cucumber Slices',       category:'Snack', ingredients:'cucumber, salt',                            diet_type:'vegan',  notes:null },
  { item_name:'Apple Slices',          category:'Snack', ingredients:'apple',                                     diet_type:'vegan',  notes:null },
  { item_name:'Yogurt Parfait',        category:'Snack', ingredients:'yogurt, granola',                           diet_type:'veg',    notes:null },
  { item_name:'Energy Balls',          category:'Snack', ingredients:'oats, peanut butter, honey',                diet_type:'veg',    notes:'https://www.youtube.com/watch?v=RFtMGEe9Aow' },
  { item_name:'Pretzels',             category:'Snack', ingredients:'pretzels',                                  diet_type:'vegan',  notes:null },
  { item_name:'Milk Glass',            category:'Snack', ingredients:'milk',                                      diet_type:'veg',    notes:null },
  { item_name:'Chips',                category:'Snack', ingredients:'potatoes, oil',                             diet_type:'vegan',  notes:null },
  { item_name:'Salsa & Chips',         category:'Snack', ingredients:'tortilla chips, tomato',                    diet_type:'vegan',  notes:null },
  { item_name:'Roasted Nuts',          category:'Snack', ingredients:'nuts, salt',                                diet_type:'vegan',  notes:null },
  { item_name:'Frozen Grapes',         category:'Snack', ingredients:'grapes',                                    diet_type:'vegan',  notes:null },
  { item_name:'Fruit Smoothie',        category:'Snack', ingredients:'berries, banana',                           diet_type:'vegan',  notes:'https://www.youtube.com/watch?v=2OVvP_KMz2k' },
  { item_name:'Peanut Butter Crackers',category:'Snack', ingredients:'peanut butter, crackers',                   diet_type:'vegan',  notes:null },
]
